//Regions
export const GET_REGIONS_REQUEST = 'GET_REGIONS_REQUEST'
export const GET_REGIONS_SUCCESS = 'GET_REGIONS_SUCCESS'
export const GET_REGIONS_ERROR = 'GET_REGIONS_ERROR'
export const GET_REGIONS_RESET = 'GET_REGIONS_RESET'
export const DISMISS_REGIONS_ERROR = 'DISMISS_REGIONS_ERROR'

//Servers
export const GET_SERVERS_REQUEST = 'GET_SERVERS_REQUEST'
export const GET_SERVERS_SUCCESS = 'GET_SERVERS_SUCCESS'
export const GET_SERVERS_ERROR = 'GET_SERVERS_ERROR'
export const GET_SERVERS_RESET = 'GET_SERVERS_RESET'
export const DISMISS_SERVERS_ERROR = 'DISMISS_SERVERS_ERROR'
export const GET_SERVER_REQUEST = 'GET_SERVER_REQUEST'
export const GET_SERVER_SUCCESS = 'GET_SERVER_SUCCESS'
export const GET_SERVER_ERROR = 'GET_SERVER_ERROR'
export const GET_STATS_REQUEST = 'GET_STATS_REQUEST'
export const GET_STATS_SUCCESS = 'GET_STATS_SUCCESS'
export const GET_STATS_ERROR = 'GET_STATS_ERROR'

//Users
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS'
export const SAVE_USER_ERROR = 'SAVE_USER_ERROR'
export const DISMISS_USER_ERROR = 'DISMISS_USER_ERROR'
export const DISMISS_USER_SUCCESS = 'DISMISS_USER_SUCCESS'
export const SET_USER_PARAMS = 'SET_USER_PARAMS'
export const SEND_LOCAL_CREDENTIALS = 'SEND_LOCAL_CREDENTIALS';

//Settings
export const GET_SETTINGS_REQUEST = 'GET_SETTINGS_REQUEST'
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS'
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR'
export const GET_SETTINGS_RESET = 'GET_SETTINGS_RESET'
export const DISMISS_SETTINGS_ERROR = 'DISMISS_SETTINGS_ERROR'
export const SET_THRESHOLDS_SETTING = 'SET_THRESHOLDS_SETTING'
export const SET_REGION_SETTING = 'SET_REGION_SETTING'
export const SET_GEN_SETTING = 'SET_GEN_SETTING'
export const SAVE_SETTINGS = 'SAVE_SETTINGS'
export const SAVE_SUCCESS = 'SAVE_SUCCESS'
export const SET_ADFS_SETTING = 'SET_ADFS_SETTING'
export const DELETE_ADFS = 'DELETE_ADFS'
export const RESET_FLAGS = 'RESET_FLAGS'
